name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - back_stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

  # pages/credential.py 설정 
  # .env 설정 
  # host 설정 
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@43.203.27.185 << 'EOF'
        source /home/ubuntu/miniconda3/bin/activate llm-env

        echo "Conda llm-env Activated"

        cd ${{ secrets.APP_DIR }}

        # 최신 코드 가져오기
        git pull origin back_stage

        echo "${{ secrets.ENV }}" > .env

        echo "${{ secrets.CREDENTIALS }}" > ./pages/credentials.py

        echo "Secrets Applied"

        # 실행 중인 uvicorn 프로세스 종료 (포트 충돌 방지)
        if lsof -i:8000; then
          echo "FastAPI 애플리케이션이 실행 중입니다. 종료합니다."
          pkill -f "uvicorn main:app"
        fi

        # FastAPI 실행
        # nohup uvicorn main:app --reload > fastapi.log 2>&1 &
        nohup python main.py

        echo "FastAPI가 성공적으로 실행되었습니다."
        EOF